const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

const root = path.resolve(__dirname, '..');
const envDir = path.join(root, 'src', 'environments');

if (!fs.existsSync(envDir)) fs.mkdirSync(envDir, { recursive: true });

// Capture process.env BEFORE dotenv touches it (Vercel/CI vars live here)
const ciEnv = { ...process.env };

function loadEnvFile(file) {
  try {
    return dotenv.parse(fs.readFileSync(path.join(root, file)));
  } catch {
    return {};
  }
}

const devVars = loadEnvFile('.env');
const prodVars = loadEnvFile('.env.production');

// CI/Vercel process.env wins; file vars are local fallback
function resolve(key, fileVars) {
  return ciEnv[key] || fileVars[key] || '';
}

function writeEnv(filename, vars, production) {
  const apiUrl = resolve('API_URL', vars);
  const content = `// Auto-generated by scripts/set-env.js — do not edit manually
export const environment = {
  production: ${production},
  apiUrl: '${apiUrl}',
};
`;
  fs.writeFileSync(path.join(envDir, filename), content);
  console.log(`Generated ${filename} — API_URL=${apiUrl || '(empty, uses proxy)'}`);
}

writeEnv('environment.ts', devVars, false);
writeEnv('environment.prod.ts', prodVars, true);
